- name: Install packages
  become: true
  apt:
    name: [ "build-essential", "zlib1g-dev", "libssl-dev", "zip", "unzip", "tree", "tldr"]
  tags:
    - install
    - core
- name: Install ZSH
  apt: name=zsh
  become: true
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
