- name: Install packages
  become: true
  apt:
    name: [ "build-essential", "zlib1g-dev", "libssl-dev", "zip", "unzip", "tree", "tldr"]
  tags:
    - install
    - core
    - apt
- name: Install ZSH
  apt: name=zsh
  become: true
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
- name: Installing stow
  apt: name=stow
  become: true
  tags:
    - install
    - dotfiles
    - stow
    - apt
- name: Update Neovim apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:neovim-ppa/unstable"
  tags:
    - install
    - nvim
    - apt
- name: Install neovim packages
  become: true
  apt:
    name: [ "neovim" ]
  tags:
    - install
    - nvim
    - apt
- name: Install zlib1g
  become: true
  apt:
    name: [zlib1g, "libffi-dev", "liblzma-dev", "libbz2-dev", "libreadline-dev", "libpq-dev", "libsqlite3-dev", "python3-tk", "pipx"]
  tags:
    - install
    - python
    - apt
- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "tldr", "ripgrep", "jq", "parallel" ]
  tags:
    - install
    - productivity
    - apt
