- name: Update homebrew Mac
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
    - install
    - core
    - brew

- name: Install homebrew packages
  homebrew:
    name: 
      - "tree"
      - "tldr"
      - "tmux"
      - "wireshark"
      - "fzf"
      - "tldr"
      - "ripgrep"
      - "jq"
      - "parallel"
      - "unzip"
      - "openssl"
      - "zoxide"
      - "cmake"
      - "kind"
    state: latest
  tags:
    - install
    - core
    - brew

- name: Install homebrew stow packages
  homebrew:
    name: ["stow"]
    state: latest
  tags:
    - install
    - dotfiles
    - stow
    - brew

- name: Install homebrew nvm packages
  homebrew:
    name: ["nvm"]
    state: latest
  tags:
    - install
    - nvm
    - brew

- name: Install homebrew go packages
  homebrew:
    name: ["go"]
    state: latest
  tags:
    - install
    - go
    - brew

- name: Install homebrew python packages
  homebrew:
    name: ["pyenv", "pipx"]
    state: latest
  tags:
    - install
    - python
    - brew

- name: Install homebrew stow packages
  homebrew:
    name: 
      - "postgresql"
      # - "tursodatabase/tap/turso"
      # - "supabase/tap/supabase"
    state: latest
  tags:
    - install
    - db
    - brew

- name: Install homebrew cask packages
  homebrew:
    name:
      - "homebrew/cask/snowflake-snowsql"
    state: latest
  tags:
    - install
    - cask
    - brew
    - db

- name: Tap a Homebrew repository, for cask-fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
  tags:
    - install
    - cask
    - brew

- name: Install homebrew cask packages
  homebrew:
    name:
      - "homebrew/cask/arc"
      - "homebrew/cask/obsidian"
      - "homebrew/cask/docker"
      - "homebrew/cask/iterm2"
      - "homebrew/cask/postman"
      - "homebrew/cask/whatsapp"
      - "homebrew/cask/google-cloud-sdk"
      - "homebrew/cask/discord"
      - "homebrew/cask/slack"
      - "font-jetbrains-mono"
    state: latest
  tags:
    - install
    - cask
    - brew
