- name: Ensure /opt/oracle
  become: true
  file:
    dest: "/opt/oracle"
    state: directory
- name: Download instant client package
  become: true
  shell: "cd /opt/oracle && curl -o instant-client.zip https://download.oracle.com/otn_software/linux/instantclient/2113000/instantclient-basic-linux.x64-21.13.0.0.0dbru.zip && unzip instant-client.zip && rm -rf instant-client.zip"
  tags:
    - install
    - oracle-instant-client

# TODO UPDATE FOR MAC
# curl -o instant-client.dmg https://download.oracle.com/otn_software/mac/instantclient/233023/instantclient-basic-macos.arm64-23.3.0.23.09-1.dmg
# hdiutil mount instant-client.dmg 
# cd /Volumes/instantclient-basic-macos.arm64-23.3.0.23.09
# sh ./install_ic.sh
# cd /opt/oracle
# /usr/bin/hdiutil unmount /Volumes/instantclient-basic-macos.arm64-23.3.0.23.09
# rm instant-client.dmg
