- name: Install zlib1g
  become: true
  apt:
    name: [zlib1g]
  tags:
    - install
    - python
- name: Check that the pyenv exists
  stat:
    path: $HOME/.pyenv
  register: pyenv_stats
  tags:
    - install
    - python
- name: Install pyenv
  shell: curl https://pyenv.run | bash
  when: pyenv_stats.stat.exists == False
  tags:
    - install
    - python
- name: Install python
  shell: pyenv install 3.10.4
  tags:
    - install
    - python
