# TODO SOME OF THESE SHOULDNT RUN ON MAC
- name: Check that the pyenv exists
  stat:
    path: $HOME/.pyenv
  register: pyenv_stats
  tags:
    - install
    - python
- name: Install pyenv
  shell: curl https://pyenv.run | bash
  when: pyenv_stats.stat.exists == False
  tags:
    - install
    - python
- name: Check that the python exists
  stat:
    path: $HOME/.pyenv/versions/3.10.13
  register: python_stats
  tags:
    - install
    - python
- name: Install python
  shell: pyenv install 3.10.13 && pyenv global 3.10.13
  when: python_stats.stat.exists == False
  tags:
    - install
    - python
