- name: Ensure nom dir 
  file:
    dest: "~/.nom"
    state: directory
  tags:
    - install
    - rss 

- name: Install Nom
  shell: cd ~/.nom && curl -L https://github.com/guyfedwards/nom/releases/download/v2.6.0/nom_2.6.0_darwin_arm64.tar.gz | tar -xzvf -
  tags:
    - install
    - rss 
