- name: Check that the pyenv exists
  stat:
    path: $HOME/.sdkman
  register: sdkman_stats
  tags:
    - install
    - sdkman
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash > /dev/null 2>&1
  when: sdkman_stats.stat.exists == False
  tags:
    - install
    - sdkman
- name: Source sdkman
  shell: . "$HOME/.sdkman/bin/sdkman-init.sh" 
  tags:
    - install
    - sdkman
- name: Install Java 23
  shell: sdk install java 23.ea.10-open
  tags:
    - install
    - sdkman
