- name: Check that the pyenv exists
  stat:
    path: $HOME/.sdkman
  register: sdkman_stats
  tags:
    - install
    - sdkman
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" > /dev/null 2>&1
  # when: sdkman_stats.stat.exists == False
  tags:
    - install
    - sdkman
