- name: Basic usage
  ansible.builtin.debug:
    msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "./ssh/id_personal"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_personal"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "./ssh/id_personal.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_personal.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
- name: Set temporary ssh config
  copy:
    src: "./ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
  tags:
    - dotfiles
    - install
    - ssh
- name: Ensure personal directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/personal"
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Clone keep your secrets
  ansible.builtin.git:
    repo: 'git@github.com:YourAverageMoron/keep-your-secrets.git'
    dest: "{{ lookup('env', 'HOME') }}/personal/keep-your-secrets"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - ssh
- name: Install all ssh keys
  copy:
    src: "$HOME/personal/keep-your-secrets/ssh/!(*@(config|.pub))"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install all ssh keys public
  copy:
    src: "$HOME/personal/keep-your-secrets/ssh/*.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
- name: Install all ssh keys public
  copy:
    src: "$HOME/personal/keep-your-secrets/ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
