- name: Basic usage
  ansible.builtin.debug:
    msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "./ssh/id_personal"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_personal"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "./ssh/id_personal"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_personal.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
