- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "tldr", "ripgrep", "jq", "parallel" ]
  tags:
    - install
    - productivity
- name: Install tmux package manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
- Install zoxide:
  shell: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
  tags:
    - install
    - productivity
