- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true
  tags: [ 'install', 'productivity', 'dotfiles', 'zsh' ]
- name: Check that the oh my zsh exists
  stat:
    path: $HOME/.oh-my-zsh
  register: oh_my_stats
  tags: [ 'install', 'productivity', 'dotfiles', 'zsh' ]
- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags: [ 'install', 'productivity', 'dotfiles', 'zsh' ]
  when: oh_my_stats.stat.exists == False
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: [ 'install', 'productivity', 'dotfiles', 'zsh' ]
- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags: [ 'install', 'productivity', 'dotfiles', 'zsh' ]
